### ISSUE TITLE
Crash on second invocation

### ISSUE THREAD

**Issue by michaelswe** [lwansbrough/react-native-camera#426]
### Steps to reproduce
1. Open a view with react-native-camera
2. N.B. Not necessary to capture picture
3. Close view
4. Open view again
### Expected behaviour

I'd expect the same behavior as at the first invocation.
### Actual behaviour

Crash.

```
- (void)setCaptureQuality:(NSString *)quality
{
    if (quality) {
        [self.session beginConfiguration];
        if ([self.session canSetSessionPreset:quality]) {
            self.session.sessionPreset = quality;
        }
        [self.session commitConfiguration];
    }
}
```

At _[self.session commitConfiguration]_ XCode reports "EXC_BAD_ACCESS"
### Environment
- **Node.js 6.4**:
- **React Native 0.33**:
- **iOS 10.0, simulator
### react-native-camera

**Version**: lwansbrough/react-native-camera  (6074ec3)
_This is the version with the simulator fix_

**Comment by furkancelik** [comment]
I'm having the same problem too...!

**Comment by michaelswe** [comment]
N.B. the problem only exists in the simulator. Works fine on device.

**Comment by JoschaP** [comment]
same problem here

**Comment by andrerfneves** [comment]
This is relating to iOS 10.0. I fixed the issue with this inside Info.plist

``` 
<key>NSCameraUsageDescription</key>
<string>This app uses the camera.</string>
```

The string can really be anything you want, it'll display when the app launches and asks for permissions to use the camera.

**Comment by ibussieres** [comment]
@andrerfneves it does not fix for me. The second invocation crashes. I have the the NSCameraUsageDescription key set in my .plist files.

**Comment by andrerfneves** [comment]
@ibussieres I didn't run into second invocation issues. But whenever I flipped the camera to the front camera the app crashed. I had to add the same key and string pair on the .plist file but for the Microphone native properties.

```
<key>NSCameraUsageDescription</key>
<string>This app uses the camera.</string>
<key>NSMicrophoneUsageDescription</key>
<string>This app uses the microphone.</string>
```

Not sure if this will fix your issue, but this is what helped me solve it.

**Comment by michaelswe** [comment]
As this only happens in the simulator I'm guessing that there is something more that needs to be wrapped in an `#if !(TARGET_IPHONE_SIMULATOR)` _(see 6074ec3)_. Maybe there is something that should be initialized only once per session. Unfortunately I don't know Objective C, so I can't look into it.

**Comment by JoschaP** [comment]
@andrerfneves it does not fix it for me, too.

I've added both to the plist file:

<key>NSCameraUsageDescription</key>
<string>This app uses the camera.</string>
<key>NSMicrophoneUsageDescription</key>
<string>This app uses the microphone.</string>



breaks at line: 988 of RCTCameraManager
[self.session commitConfiguration];


2016-09-28 14:16:48.562 [info][tid:main][RCTCameraManager.m:270] Error setting property 'captureAudio' of RCTCamera with tag #342: capturing audio

**Comment by ibussieres** [comment]
@andrerfneves thanks for the hinters, unfortunately it does not work. Besides, I am using this package only for barcode scanning so I had disabled the microphone. I think @michaelswe has put the finger on the type of problem that we need to surface up, I'm not too good with Objective-C either, but I'll try to look into something (yet hoping someone with better Objective-C skills will, too ;) )

**Comment by chrisnojima** [comment]
I have the same problem. It renders fine but if I switch screens and come back it'll crash. I'm running the iPhone 7 iOS 10.0 simulator. I have only the NSCameraUsageDescription as i have autoCapture turned off (and changing the microphone setting seems to change nothing regarding this issue).

For me it crashes at: https://github.com/lwansbrough/react-native-camera/blob/master/ios/RCTCameraManager.m#L988

![screen shot 2016-09-28 at 5 52 34 pm](https://cloud.githubusercontent.com/assets/516435/18933784/6304937a-85a4-11e6-8bcf-294bb00118b6.png)

**Comment by comountainclimber** [comment]
I am experiencing a crash at the same place @chrisnojima have permission in info.plist for both camera and microphone... 

This crash appears to only occur on simulator as others have stated above

**Comment by miclaus** [comment]
+1 also have permissions in Info.plist

**Comment by shahen94** [comment]
@michaelswe try to put into `<Camera />` component empty <View /> .
Like this.

```
<Camera>
  <View />
</Camera>
```

**Comment by RGBz** [comment]
@shahen94 did that work for you? I'm still getting a crash at the same line.

**Comment by shahen94** [comment]
@RGBz It works for me

**Comment by rgoldiez** [comment]
Added a `<View />` inside of `<Camera>` and it still crashes in the simulator on the second invocation.

**Comment by comountainclimber** [comment]
(this issue only occurs in simulator)

**Comment by uncle-T0ny** [comment]
I have crash on setCaptureQuality and this bug reproduces on real device. 
I tried to use different component properties, but this has not any effect.
![screen shot 2016-11-11 at 5 39 35 pm](https://cloud.githubusercontent.com/assets/11603037/20220357/e1492c9c-a835-11e6-91ef-1f9c6664c6bb.png)

[IOS camera crash.txt](https://github.com/lwansbrough/react-native-camera/files/586116/IOS.camera.crash.txt)

And I don't know how to solve it, could anyone help me, please?

**Comment by baskan** [comment]
I dunno if its releated but I put camera inside a wrapping container and add a shouldComponentUpdate() { return false; } now working fine on actual android device havent tested on an actual iOS device but its worth a try.

**Comment by AndrewDeveloper** [comment]
Not sure how and why it works, but @shahen94 fix helped me

**Comment by kesha-antonov** [comment]
<img width="912" alt="screen shot 2016-11-12 at 16 36 48" src="https://cloud.githubusercontent.com/assets/11584712/20238180/4c3806f2-a8f6-11e6-927d-61e246005350.png">

Got this too. Sadly I don't have enough knowledge for now to fix this(

Hoping you can fix this guys.

**Comment by uncle-T0ny** [comment]
@kesha-antonov I've just fixed the issue. The problem really was with NSMicrophoneUsageDescription permission. Check that application has camera and microphone permissions before you render the Camera component. Also be aware that microphone permission request not work on iPhone simulators. Good luck to you.

**Comment by kesha-antonov** [comment]
@uncle-T0ny Thanks!
And maybe ```captureAudio={false}``` will be good when use camera only for photos. Hence do not need microphone permissions.

**Comment by rgoldiez** [comment]
I did not add the microphone permission because I set video to false. I use it just for still images. No crashes here.

**Comment by jqn** [comment]
Same here I have captureAudio={false} because I don't need to capture audio. Everything works fine in iOS but the Android version crashes.

**Comment by Okipa** [comment]
I am experiencing the same issue this issue on Android with the v0.6.
I have specified `captureAudio={false}` and this is still crashing on Android.
I tried to add `<uses-permission android:name="android.permission.RECORD_AUDIO" />` on my AndroidManifest.xml file and the crash still happens.
Is there a way to avoid this problem ?

**Comment by Geforceyu** [comment]
I'm having the same problem too...! I add this key to info.plist ,was Iphone
